### PR TITLE
Development, Files Cleanup

### PR DESCRIPTION
**Pull request by AnthonyWaithaka**
#### What does this PR do?
Implements RESTful workflow for the API's endpoints.
Adds details of features to the README
#### How should this be manually tested?
Register a new user and login on an active server using Postman.
Add the generated token to a header with prefix "Bearer " for authentication. The header should be named 'Authorization'.
#### Any background context you want to provide?
The project requires several more features which may be committed before the merge.
These are:
- Searching
- Pagination with limits

### CODE REVIEW

**Comment by briankabiro** [comment]
Advise you to use imperative mood in subject line. Like how you categorize the commits. Subject lines are very informative.

**Comment by AnthonyWaithaka** [comment]
Thank you, @briankabiro. I'll check out the git documentation for that and other methods for making informative commit messages

**Comment by ogomb** [comment]
liked the way you have grouped your views. Its awesome 😄

**Comment by ridgekimani** [comment]
Nice commits.. Integrate travis ci so that I see your tests running.. Otherwise great job...

**Comment by AnthonyWaithaka** [comment]
Thanks @ridgekimani. I'll alert you when that's done.

**Comment by AnthonyGW** [comment]
@ridgekimani I added build and coverage badges to the readme in the new branch 'feedback'

**Pull request merged**
